// <auto-generated />
using HOANGQUANGTRUONG_PH53664.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HOANGQUANGTRUONG_PH53664.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250119073225_C3")]
    partial class C3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HOANGQUANGTRUONG_PH53664.Models.SanPham", b =>
                {
                    b.Property<int>("MaSP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSP"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenSP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSP");

                    b.ToTable("SanPhams");
                });

            modelBuilder.Entity("HOANGQUANGTRUONG_PH53664.Models.SanPhamChiTiet", b =>
                {
                    b.Property<int>("MaSPCT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSPCT"));

                    b.Property<string>("KichThuoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaSP")
                        .HasColumnType("int");

                    b.Property<string>("MauSac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSPCT");

                    b.HasIndex("MaSP")
                        .IsUnique();

                    b.ToTable("SanPhamChiTiets");
                });

            modelBuilder.Entity("HOANGQUANGTRUONG_PH53664.Models.SanPhamChiTiet", b =>
                {
                    b.HasOne("HOANGQUANGTRUONG_PH53664.Models.SanPham", "sanPham")
                        .WithOne("sanPhamChiTiet")
                        .HasForeignKey("HOANGQUANGTRUONG_PH53664.Models.SanPhamChiTiet", "MaSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("sanPham");
                });

            modelBuilder.Entity("HOANGQUANGTRUONG_PH53664.Models.SanPham", b =>
                {
                    b.Navigation("sanPhamChiTiet")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
